"""
Shared data transformation utilities for converting PostgreSQL data to API format
"""

def convert_postgres_to_camelcase(data_dict):
    """Convert PostgreSQL lowercase column names to camelCase for API compatibility"""
    column_mapping = {
        'companyname': 'companyName',
        'mktcap': 'marketCap',
        'exchangeshortname': 'exchangeShortName',
        'fulltimeemployees': 'fullTimeEmployees',
        'ipodate': 'ipoDate',
        'volavg': 'avgVolume',
        'lastdiv': 'dividendYield',
        'isactivelytrading': 'isActivelyTrading',
        'isadr': 'isAdr',
        'isetf': 'isEtf',
        'isfund': 'isFund',
        'defaultimage': 'defaultImage',
        'calendaryear': 'calendarYear',
        'costofrevenue': 'costOfRevenue',
        'grossprofit': 'grossProfit',
        'grossprofitratio': 'grossProfitRatio',
        'researchanddevelopmentexpenses': 'researchAndDevelopmentExpenses',
        'generalandadministrativeexpenses': 'generalAndAdministrativeExpenses',
        'sellingandmarketingexpenses': 'sellingAndMarketingExpenses',
        'operatingexpenses': 'operatingExpenses',
        'costandexpenses': 'costAndExpenses',
        'interestexpense': 'interestExpense',
        'depreciationandamortization': 'depreciationAndAmortization',
        'ebitdaratio': 'ebitdaRatio',
        'operatingincome': 'operatingIncome',
        'operatingincomeratio': 'operatingIncomeRatio',
        'totalotherincomeexpensesnet': 'totalOtherIncomeExpensesNet',
        'incomebeforetax': 'incomeBeforeTax',
        'incomebeforetaxratio': 'incomeBeforeTaxRatio',
        'incometaxexpense': 'incomeTaxExpense',
        'netincome': 'netIncome',
        'netincomeratio': 'netIncomeRatio',
        'epsdiluted': 'epsDiluted',
        'weightedaverageshsout': 'weightedAverageShsOut',
        'weightedaverageshsoutdil': 'weightedAverageShsOutDil',
        'accepteddate': 'acceptedDate',
        'fillingdate': 'fillingDate',
        'finallink': 'finalLink',
        'sellinggeneralandadministrativeexpenses': 'sellingGeneralAndAdministrativeExpenses',
        'reportedcurrency': 'reportedCurrency',
        'fiscalyear': 'fiscalYear',
        
        # TTM field mappings
        'revenuettm': 'revenueTTM',
        'costofrevenuettm': 'costOfRevenueTTM',
        'grossprofitttm': 'grossProfitTTM',
        'operatingexpensesttm': 'operatingExpensesTTM',
        'operatingincomettm': 'operatingIncomeTTM',
        'incomebeforetaxttm': 'incomeBeforeTaxTTM',
        'incometaxexpensettm': 'incomeTaxExpenseTTM',
        'netincomettm': 'netIncomeTTM',
        'epsttm': 'epsTTM',
        'epsdilutedttm': 'epsDilutedTTM',
        'cashttm': 'cashTTM',
        'currentassetsttm': 'currentAssetsTTM',
        'totalassetsttm': 'totalAssetsTTM',
        'currentliabilitiesttm': 'currentLiabilitiesTTM',
        'longtermdebtttm': 'longTermDebtTTM',
        'totalliabilitiesttm': 'totalLiabilitiesTTM',
        'totaldebtttm': 'totalDebtTTM',
        'stockholdersequityttm': 'stockholdersEquityTTM',
        'workingcapitalttm': 'workingCapitalTTM',
        'operatingcashflowttm': 'operatingCashFlowTTM',
        'investingcashflowttm': 'investingCashFlowTTM',
        'financingcashflowttm': 'financingCashFlowTTM',
        'capexttm': 'capexTTM',
        'freecashflowttm': 'freeCashFlowTTM',
        'netchangeincashttm': 'netChangeInCashTTM',
        
        # Financial ratios mappings
        'priceearningsratio': 'pe',
        'pricetobookratio': 'priceToBookRatio',
        'pricetosalesratio': 'priceToSalesRatio',
        'pricetofreecashflowsratio': 'priceToFreeCashFlowRatio',
        'priceearningstogrowthratio': 'peg',
        'returnonequity': 'roe',
        'returnonassets': 'roa',
        'dividendyield': 'dividendYield',
        'dividendpayoutratio': 'dividendPayoutRatio',
        'currentratio': 'currentRatio',
        'quickratio': 'quickRatio',
        'debtequityratio': 'debtEquityRatio',
        'grossprofitmargin': 'grossProfitMargin',
        'operatingprofitmargin': 'operatingProfitMargin',
        'netprofitmargin': 'netProfitMargin',
        'cashpershare': 'cashPerShare',
        'freecashflowpershare': 'freeCashFlowPerShare',
        'interestcoverage': 'interestCoverage',
        'enterprisevalueoverebitda': 'evToEbitda',
        'evtosales': 'evToSales',
        'evtofreecashflow': 'evToFreeCashFlow',
        'evtooperatingcashflow': 'evToOperatingCashFlow',
        'bookvaluepershare': 'bookValuePerShare',
        'freecashflowyield': 'freeCashFlowYield',
        'earningsyield': 'earningsYield',
        'payoutratio': 'payoutRatio',
        
        # Key metrics mappings (alternative sources for ratios)
        'peratio': 'pe',
        'pbratio': 'priceToBookRatio',
        'enterprisevalue': 'enterpriseValue',
        'enterprisevalueoverebitda': 'evToEbitda',
        'evtosales': 'evToSales',
        'evtofreecashflow': 'evToFreeCashFlow',
        'evtooperatingcashflow': 'evToOperatingCashFlow',
        'marketcap': 'marketCap',
        'bookvaluepershare': 'bookValuePerShare',
        'netincomepershare': 'netIncomePerShare',
        'revenuepershare': 'revenuePerShare',
        'tangiblebookvaluepershare': 'tangibleBookValuePerShare',
        'workingcapital': 'workingCapital',
        'investedcapital': 'investedCapital',
        'returnontangibleassets': 'returnOnTangibleAssets',
        
        # Additional mappings from companies_financials.py
        'cashandcashequivalents': 'cashAndCashEquivalents',
        'shortterminvestments': 'shortTermInvestments',
        'netreceivables': 'netReceivables',
        'inventory': 'inventory',
        'othercurrentassets': 'otherCurrentAssets',
        'totalcurrentassets': 'totalCurrentAssets',
        'propertyplantequipmentnet': 'propertyPlantEquipmentNet',
        'goodwill': 'goodwill',
        'intangibleassets': 'intangibleAssets',
        'longterminvestments': 'longTermInvestments',
        'taxassets': 'taxAssets',
        'othernoncurrentassets': 'otherNonCurrentAssets',
        'totalnoncurrentassets': 'totalNonCurrentAssets',
        'totalassets': 'totalAssets',
        'accountspayable': 'accountsPayable',
        'shorttermdebt': 'shortTermDebt',
        'taxpayables': 'taxPayables',
        'deferredrevenue': 'deferredRevenue',
        'othercurrentliabilities': 'otherCurrentLiabilities',
        'totalcurrentliabilities': 'totalCurrentLiabilities',
        'longtermdebt': 'longTermDebt',
        'deferredrevenuenoncurrent': 'deferredRevenueNonCurrent',
        'deferredtaxliabilitiesnoncurrent': 'deferredTaxLiabilitiesNonCurrent',
        'othernoncurrentliabilities': 'otherNonCurrentLiabilities',
        'totalnoncurrentliabilities': 'totalNonCurrentLiabilities',
        'totalliabilities': 'totalLiabilities',
        'commonstock': 'commonStock',
        'retainedearnings': 'retainedEarnings',
        'accumulatedothercomprehensiveincomeloss': 'accumulatedOtherComprehensiveIncomeLoss',
        'othertotalstockholdersequity': 'otherTotalStockholdersEquity',
        'totalliabilitiesandstockholdersequity': 'totalLiabilitiesAndStockholdersEquity',
        'totalinvestments': 'totalInvestments',
        'totaldebt': 'totalDebt',
        'netdebt': 'netDebt',
        'deferredincometax': 'deferredIncomeTax',
        'stockbasedcompensation': 'stockBasedCompensation',
        'changeinworkingcapital': 'changeInWorkingCapital',
        'accountsreceivables': 'accountsReceivables',
        'accountspayables': 'accountsPayables',
        'otherworkingcapital': 'otherWorkingCapital',
        'othernoncashitems': 'otherNonCashItems',
        'netcashprovidedbyoperatingactivities': 'netCashProvidedByOperatingActivities',
        'investmentsinpropertyplantequipment': 'investmentsInPropertyPlantAndEquipment',
        'acquisitionsnet': 'acquisitionsNet',
        'purchasesofinvestments': 'purchasesOfInvestments',
        'salesmaturitiesofinvestments': 'salesMaturitiesOfInvestments',
        'otherinvestingactivites': 'otherInvestingActivites',
        'netcashusedforinvestingactivites': 'netCashUsedForInvestingActivites',
        'debtrepayment': 'debtRepayment',
        'commonstockissued': 'commonStockIssued',
        'commonstockrepurchased': 'commonStockRepurchased',
        'dividendspaid': 'dividendsPaid',
        'otherfinancingactivites': 'otherFinancingActivites',
        'netcashusedprovidedbyfinancingactivities': 'netCashUsedProvidedByFinancingActivities',
        'effectofforexchangesoncash': 'effectOfForexChangesOnCash',
        'netchangeincash': 'netChangeInCash',
        'cashatendofperiod': 'cashAtEndOfPeriod',
        'cashatbeginningofperiod': 'cashAtBeginningOfPeriod',
        'operatingcashflow': 'operatingCashFlow',
        'capitalexpenditure': 'capitalExpenditure',
        'freecashflow': 'freeCashFlow'
    }
    
    result = {}
    for key, value in data_dict.items():
        # Convert to camelCase if mapping exists, otherwise keep original
        camel_key = column_mapping.get(key.lower(), key)
        result[camel_key] = value
    return result
