#!/usr/bin/env python3
"""
Agent Configuration - Settings specific to agentic behavior

This module handles configuration for the agentic layer including:
- Iterative improvement settings
- Evaluation parameters
- Quality assessment thresholds

Note: Follow-up question generation is handled by Master Agent (gpt-4.1-mini-2025-04-14),
not by a separate model configuration.
"""

import os
import logging

logger = logging.getLogger(__name__)


class AgentConfig:
    """Configuration management for the Agent system.

    The agent uses iterative self-improvement to generate high-quality answers.
    Evaluation settings control when the agent stops iterating.
    """
    
    def __init__(self):
        self.config = {
            # Iterative improvement settings
            "max_iterations": int(os.getenv("RAG_MAX_ITERATIONS", "4")),
            "min_confidence_threshold": 0.90,  # Very high bar to stop early - use all iterations
            "min_completeness_threshold": 0.90,  # Very high bar to stop early - use all iterations
            
            # Evaluation model settings (quality assessment only)
            "evaluation_model": "gpt-4.1-mini-2025-04-14",
            "evaluation_temperature": 0.05,  # Lower temperature for more consistent/strict evaluation
            "evaluation_max_tokens": 1500,
            
            # Note: Follow-up questions are generated by Master Agent (gpt-4.1-mini-2025-04-14)
            # in agent/master_agent.py, not by a separate model call
            
            # Quality thresholds for iteration decisions (very strict - favor iteration)
            "excellent_threshold": 0.95,  # Near perfect to stop early - use available iterations
            "good_threshold": 0.80,       # Even "good" should iterate if iterations remain
            "poor_threshold": 0.60,       # Below this, definitely iterate
            
            # Search expansion during iterations
            "max_new_chunks_per_iteration": 5,
            "similarity_threshold_expansion": 0.25,  # Lower threshold for follow-up searches
            
            # Iteration strategy
            "aggressive_iteration": True,  # Use all available iterations unless answer is near-perfect
            "prefer_max_iterations": True,  # Favor using all iterations for comprehensive answers
        }
    
    def get(self, key: str, default=None):
        """Get configuration value."""
        return self.config.get(key, default)
    
    def __getitem__(self, key):
        """Enable dictionary-style access to config values."""
        return self.config[key]
    
    def __setitem__(self, key, value):
        """Enable dictionary-style assignment to config values."""
        self.config[key] = value
    
    def update(self, updates: dict):
        """Update multiple configuration values at once."""
        self.config.update(updates)
        logger.info(f"Updated agent configuration: {list(updates.keys())}")

